# Generated by Django 5.2.1 on 2025-05-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='w', max_length=20),
            preserve_default=False,
        ),
    ]
