# Generated by Django 5.2.1 on 2025-05-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='pid',
            new_name='username',
        ),
    ]
