# Generated by Django 5.2.1 on 2025-05-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_pid_task_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
