# Generated by Django 5.2.1 on 2025-09-19 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_img', models.ImageField(upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('desc', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('del_price', models.FloatField()),
                ('save_upto', models.FloatField()),
                ('where_to_display', models.CharField(choices=[('home', 'Home'), ('none', 'None')], default='none', max_length=10)),
                ('gaurante_rules', models.CharField(max_length=2000)),
                ('delevry_time', models.IntegerField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='images/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
            ],
        ),
    ]
