# Generated by Django 5.2.1 on 2025-09-19 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_remove_size_p_id_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='images/')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
            ],
        ),
    ]
