# Generated by Django 5.2.1 on 2025-09-19 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_remove_product_slug_alter_category_slug_productimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='del_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delevry_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gaurante_rules',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='save_upto',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='img',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='size',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecom.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, default='', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='p_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecom.product'),
        ),
        migrations.AlterField(
            model_name='size',
            name='p_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecom.product'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(default='', max_length=10),
        ),
    ]
