# Generated by Django 5.2.1 on 2025-09-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_remove_product_del_price_remove_product_delevry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='del_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
