# Generated by Django 5.2.1 on 2025-09-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
