# Generated by Django 5.2.1 on 2025-09-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_product_delivery_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='delivery_time',
            new_name='delivery_times',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in stock', 'In Stock'), ('out of stock', 'Out of Stock')], default='in stock', max_length=15),
        ),
    ]
