# Generated by Django 5.2.1 on 2025-09-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_rename_delivery_time_product_delivery_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='where',
            field=models.CharField(choices=[('bestselling', 'bestselling'), ('trending', 'trending'), ('first', 'first'), ('last', 'last')], default='none', max_length=100),
        ),
    ]
