# Generated by Django 5.2.1 on 2025-09-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_product_where'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='small_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
