# Generated by Django 5.2.1 on 2025-09-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_product_small_desc_product_small_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_category_diff',
            field=models.CharField(choices=[('jewelry', 'jewelry'), ('cosmetic', 'coesmetic'), ('skincare', 'skincare')], default='in stock', max_length=15),
        ),
    ]
