# Generated by Django 5.2.1 on 2025-09-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guarentee',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='in stock', max_length=15),
        ),
    ]
