# Generated by Django 5.2.1 on 2025-09-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_product_guarentee_product_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='save_upto',
            field=models.IntegerField(default=1),
        ),
    ]
