# Generated by Django 5.2.1 on 2025-09-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_product_save_upto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category_diff',
            field=models.CharField(choices=[('jewelry', 'jewelry'), ('cosmetic', 'coesmetic'), ('skincare', 'skincare')], default='non', max_length=15),
        ),
    ]
