# Generated by Django 5.2.1 on 2025-09-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_alter_product_main_category_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='jewelry', max_length=15),
        ),
    ]
