# Generated by Django 5.2.1 on 2025-09-21 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0019_alter_product_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand_Category',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(default='', max_length=100)),
                ('hot', models.CharField(choices=[('none', 'none'), ('hot', 'hot'), ('trending', 'trending'), ('bestselling', 'bestsellin')], default='none', max_length=150)),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='main_Category',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(default='', max_length=100)),
                ('hot', models.CharField(choices=[('none', 'none'), ('hot', 'hot'), ('trending', 'trending'), ('bestselling', 'bestsellin')], default='none', max_length=150)),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='hot',
            field=models.CharField(choices=[('none', 'none'), ('hot', 'hot'), ('trending', 'trending'), ('bestselling', 'bestsellin')], default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='jewelry', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in stock', 'In Stock'), ('out of stock', 'Out of Stock')], default='first', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecom.brand_category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category_diff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecom.main_category'),
        ),
    ]
