# Generated by Django 5.2.1 on 2025-09-21 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0020_brand_category_main_category_category_hot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_category_diff',
        ),
        migrations.AddField(
            model_name='category',
            name='main_category_diff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecom.main_category'),
        ),
    ]
