# Generated by Django 5.2.1 on 2025-09-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0022_remove_category_main_category_diff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category_diff',
            field=models.CharField(choices=[('jewelry', 'jewelry'), ('cosmetic', 'coesmetic'), ('skincare', 'skincare')], default='non', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in stock', 'In Stock'), ('out of stock', 'Out of Stock')], default='', max_length=150),
        ),
        migrations.DeleteModel(
            name='brand_Category',
        ),
        migrations.DeleteModel(
            name='main_Category',
        ),
    ]
